"""added location table

Revision ID: 08d5757c4add
Revises: fb1ebc2e6c7d
Create Date: 2023-05-01 21:17:51.595500

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '08d5757c4add'
down_revision = 'fb1ebc2e6c7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
