"""Create tenant model

Revision ID: 1bcfafeac745
Revises: c1871b4c584c
Create Date: 2023-05-15 10:36:54.676629

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1bcfafeac745'
down_revision = 'c1871b4c584c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
