"""added timestamps

Revision ID: 1e1efb7be236
Revises: 4a45e7748c47
Create Date: 2023-05-01 22:43:27.961766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e1efb7be236"
down_revision = "4a45e7748c47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business", sa.Column("created_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "business", sa.Column("updated_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "location", sa.Column("created_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "location", sa.Column("updated_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column("user", sa.Column("created_timestamp", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_timestamp", sa.DateTime(), nullable=True))
    op.drop_column("user", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user", "updated_timestamp")
    op.drop_column("user", "created_timestamp")
    op.drop_column("location", "updated_timestamp")
    op.drop_column("location", "created_timestamp")
    op.drop_column("business", "updated_timestamp")
    op.drop_column("business", "created_timestamp")
    # ### end Alembic commands ###
