"""move product table

Revision ID: 441f581b7aa5
Revises: a9595d2ceba8
Create Date: 2023-05-10 09:25:35.964128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '441f581b7aa5'
down_revision = 'a9595d2ceba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
