"""Tweak model to fix business id issue

Revision ID: 49cdd47bcb7a
Revises: eb9d026fb946
Create Date: 2023-05-12 12:56:51.284949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '49cdd47bcb7a'
down_revision = 'eb9d026fb946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_business_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'business', ['business_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_business_id_fkey', 'product', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###
