"""added location table

Revision ID: 4a45e7748c47
Revises: 08d5757c4add
Create Date: 2023-05-01 21:20:38.156038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4a45e7748c47'
down_revision = '08d5757c4add'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('business_owner_id_fkey', 'business', type_='foreignkey')
    op.create_foreign_key(None, 'business', 'user', ['user_id'], ['id'])
    op.drop_column('business', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.create_foreign_key('business_owner_id_fkey', 'business', 'user', ['owner_id'], ['id'])
    op.drop_column('business', 'user_id')
    # ### end Alembic commands ###
