"""move product table

Revision ID: 584a52d6a9d4
Revises: 441f581b7aa5
Create Date: 2023-05-10 09:27:28.748963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '584a52d6a9d4'
down_revision = '441f581b7aa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
