"""Add business reviews table

Revision ID: 6f894fb3a5c5
Revises: 1bcfafeac745
Create Date: 2023-05-24 14:30:32.350084

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "6f894fb3a5c5"
down_revision = "1bcfafeac745"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
