"""create relationship btw business and product tables

Revision ID: 739b134ca21d
Revises: f003c5824687
Create Date: 2023-05-08 23:53:16.200424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "739b134ca21d"
down_revision = "f003c5824687"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
