"""Removed UUIDs from user table

Revision ID: 78e62b4d7f2c
Revises: 9af8a4070802
Create Date: 2023-04-26 12:53:21.154160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '78e62b4d7f2c'
down_revision = '9af8a4070802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
