"""fix for location

Revision ID: 7c2bb54f8e92
Revises: 1e1efb7be236
Create Date: 2023-05-02 13:24:43.233477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7c2bb54f8e92'
down_revision = '1e1efb7be236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
