"""added user status

Revision ID: 943d8d38edd3
Revises: 78e62b4d7f2c
Create Date: 2023-04-27 14:04:26.396813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "943d8d38edd3"
down_revision = "78e62b4d7f2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "status")
    # ### end Alembic commands ###
