"""added timestamp to user model

Revision ID: 9af8a4070802
Revises: 
Create Date: 2023-04-21 00:25:06.290579

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "9af8a4070802"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("timestamp", sa.DateTime(), nullable=True))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "timestamp")
    # ### end Alembic commands ###
