"""add ID attribute to business table

Revision ID: a3727217bd3b
Revises: 7c2bb54f8e92
Create Date: 2023-05-03 16:06:37.162370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "a3727217bd3b"
down_revision = "7c2bb54f8e92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business", "location_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business", "location_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
