"""move product table

Revision ID: a9595d2ceba8
Revises: 739b134ca21d
Create Date: 2023-05-10 09:21:45.724401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a9595d2ceba8'
down_revision = '739b134ca21d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
