"""Breaking changes, add profile, but retain user table

Revision ID: cb2999cb5b64
Revises: 8b2d99fac8ab
Create Date: 2023-05-25 22:39:36.152538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cb2999cb5b64'
down_revision = '8b2d99fac8ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'profile', ['profile_id'], ['id'])
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    op.drop_column('review', 'profile_id')
    # ### end Alembic commands ###
