"""Rename review field to description

Revision ID: e535d611e2b0
Revises: 6f894fb3a5c5
Create Date: 2023-05-25 21:12:08.712977

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e535d611e2b0'
down_revision = '6f894fb3a5c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('review', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('review', 'description')
    # ### end Alembic commands ###
