"""added location table

Revision ID: fb1ebc2e6c7d
Revises: 690087bff275
Create Date: 2023-05-01 21:11:55.523162

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "fb1ebc2e6c7d"
down_revision = "690087bff275"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
